# PostgreSQL
# adapter       : 'postgres'
# location      : 'localhost/dbname'
# auto_migrate  : 'true'
# auto_upgrade  : 'true'

# MongoDB
# adapter       : 'mongo'
# location      : 'localhost/dbname'

# MySQL
# adapter       : 'mysql'
# location      : 'localhost/dbname'
development:
  base_url: #INSERT URL API ADDRESS HERE e.g www.lemon-swirl.com:4567
